spring:
  ai:
    openai:
      base-url: https://api.openai.com
      api-key: somekey
      chat:
        options:
          model: gpt-4.1-mini
  profiles:
    active: local
  datasource:
    url: someurl
    username: username
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jdbc:
    template:
      query-timeout: 30